name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id:   previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: ${GITHUB_REF#refs/*/} # Optional fallback tag to use when no tag can be found
      - uses: ruby/setup-ruby@v1
      - run: gem install github_changelog_generator -v 1.16.3
      - run: |
             github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} \
               --release-url "https://github.com/${{ github.repository }}/releases/tag/${GITHUB_REF#refs/*/}" \
               --release-branch actions-goreleaser \
               --no-compare-link \
               --since-tag ${{ steps.previoustag.outputs.tag }}
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

#  goreleaser:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16
#      - uses: actions/download-artifact@v2
#        with:
#          name: changelog
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v2
#        with:
#          distribution: goreleaser
#          # version:      latest
#          args:         release --rm-dist --release-notes=CHANGELOG.md
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
